In [1]:
import torch

In [2]:
x = torch.empty(2, 3)
print(x)

tensor([[1.6217e-19, 1.4586e-19, 1.8617e+25],
        [1.6212e-19, 1.4586e-19, 1.1578e+27]])


In [3]:
x = torch.rand(2, 3)
print(x)

tensor([[0.4326, 0.2909, 0.2214],
        [0.6284, 0.6132, 0.6851]])


In [4]:
x = torch.zeros(2, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([[5.5, 3],[2.2,5]])
print(x)

tensor([[5.5000, 3.0000],
        [2.2000, 5.0000]])


In [7]:
# 返回的torch.Size其实就是一个tuple, 支持所有tuple的操作。
print(x.size())
print(x.shape)

torch.Size([2, 2])
torch.Size([2, 2])


In [8]:
# 返回的tensor默认具有相同的torch.dtype和torch.device
x = x.new_ones(2, 3, dtype=torch.float64)  
print(x)

# 指定新的数据类型
x = torch.randn_like(x, dtype=torch.float) 
print(x) 


tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1539,  0.6540, -0.8830],
        [ 0.5230,  0.7018,  0.1763]])


In [9]:
# 加法形式一
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x + y)

# 加法形式二
print(torch.add(x, y))

# 加法形式三，inplace（原地操作）y.add_(x) 
print(y)

# PyTorch操作的inplace版本都有后缀“_” , 例如x.copy_(y), x.t_()


tensor([[0.9792, 1.5760, 1.1113],
        [1.5090, 1.3637, 1.1922]])
tensor([[0.9792, 1.5760, 1.1113],
        [1.5090, 1.3637, 1.1922]])
tensor([[0.3596, 0.7052, 0.3851],
        [0.5783, 0.4170, 0.3748]])


In [20]:
x = torch.ones(2, 3)
y = x[0, :]
print(x,y)
y += 1
print(x,y)
print(x[0, :]) # 源tensor也被改了


tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([1., 1., 1.])
tensor([[2., 2., 2.],
        [1., 1., 1.]]) tensor([2., 2., 2.])
tensor([2., 2., 2.])


In [18]:
y = x.view(6)
z = x.view(-1, 2)  # -1所指的维度可以根据其他维度的值推出来
print(y,z)
print(x.size(), y.size(), z.size())

tensor([2., 2., 2., 1., 1., 1.]) tensor([[2., 2.],
        [2., 1.],
        [1., 1.]])
torch.Size([2, 3]) torch.Size([6]) torch.Size([3, 2])


In [21]:
x += 1
print(x)
print(y) # y也加了1


tensor([[3., 3., 3.],
        [2., 2., 2.]])
tensor([3., 3., 3.])


In [23]:
x1=x.reshape(3,2)
print(x1)
x_cp = x.clone().view(6)
x -= 1
print(x)
print(x_cp)


tensor([[2., 2.],
        [2., 1.],
        [1., 1.]])
tensor([[1., 1., 1.],
        [0., 0., 0.]])
tensor([2., 2., 2., 1., 1., 1.])


In [25]:
#arange返回大小为 (end-start)/step, [start,end) 

x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [26]:
a = torch.ones(3)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)


tensor([1., 1., 1.]) [1. 1. 1.]
tensor([2., 2., 2.]) [2. 2. 2.]
tensor([3., 3., 3.]) [3. 3. 3.]


In [27]:
import numpy as np
a = np.ones(3)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1.] tensor([1., 1., 1.], dtype=torch.float64)
[2. 2. 2.] tensor([2., 2., 2.], dtype=torch.float64)
[3. 3. 3.] tensor([3., 3., 3.], dtype=torch.float64)


In [28]:
c = torch.tensor(a)
a += 1
print(a, c)


[4. 4. 4.] tensor([3., 3., 3.], dtype=torch.float64)


In [29]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型


tensor([[2, 3]], device='cuda:0')
tensor([[2., 3.]], dtype=torch.float64)


In [30]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [31]:
y = x + 2
print(y)
print(y.grad_fn)


tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [32]:
z = y * y * 3
out = z.mean()
print(z)
print(out)


tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [33]:
a = torch.randn(2, 2)     # 缺失情况下默认 requires_grad = False
a = ((a * 3) / (a - 1))
print(a.requires_grad)   # False
a.requires_grad_(True)
print(a.requires_grad)   # True
b = (a * a).sum()
print(b.grad_fn)


False
True


In [36]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()
out.backward()  # 等价于 out.backward(torch.tensor(1.))

print(x.grad)


tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [35]:
# 再来反向传播一次，注意grad是累加的
out2 = x.sum()
out2.backward()
print(x.grad)

out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])
tensor([[1., 1.],
        [1., 1.]])


In [37]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x
z = y.view(2, 2)
print(z)


tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward0>)


In [38]:
v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)
print(x.grad)


tensor([2.0000, 0.2000, 0.0200, 0.0020])
