In [15]:
import torch

# 检测torch环境是否可用
print(torch.__version__)
print(torch.cuda.is_available())

1.12.1+cu116
True


# 1.
使用 Tensor初始化一个1x3的矩阵 M 和一个2x1的矩阵 N，对两短阵进行减法操作(要求实现三种不同的形式)，给出结果并分析三种方式的不同(如果出现报错，分析报错的原因)，司时需要指出在计算过程中发生了什么

In [19]:
# 第一题
print('*'*20, '第一题', '*'*20)
# 初始化 A 和 B
M = torch.Tensor([1, 2, 3])
N = torch.Tensor([[1], [2]])

# 方式一：使用 torch.sub() 函数进行减法操作
res1 = torch.sub(M, N)

# 方式二：使用 - 运算符进行减法操作
res2 = M - N

# 方式三：使用 torch.add() 函数进行加法操作，并传递负数作为参数
res3 = torch.add(M, torch.neg(N))

# 打印结果
print("方法一:", res1)
print("方法二:", res2)
print("方法三", res3)

******************** 第一题 ********************
方法一: tensor([[ 0.,  1.,  2.],
        [-1.,  0.,  1.]])
方法二: tensor([[ 0.,  1.,  2.],
        [-1.,  0.,  1.]])
方法三 tensor([[ 0.,  1.,  2.],
        [-1.,  0.,  1.]])


### 减法方法
(1) 使用 torch.sub() 函数进行减法操作，该函数会将两个输入张量的元素逐元素相减。
(2) 使用 - 运算符进行减法操作，这种方式与第一种方式本质上是相同的，只是使用了运算符的简写形式。
(3) 使用 torch.add() 函数进行加法操作，并将 -N 作为第二个参数传递给该函数，以实现减法操作。这种方式的优点是可以将任何二元操作转换为加法操作，但是需要将其中一个参数乘以 -1。

# 2.
(1) 利用 Tensor 创建两个大小分别 3x2 和4x2的随机数矩阵P和Q，要求服从均值为0，标准差0.01为的正态分布
(2) 对第二步得到的阵 进行形状变换得到 的转置 Q^T
(3) 对上述得到的矩阵P和矩阵 Q^T 求内积

In [17]:
# 第二题
print('*'*20, '第二题', '*'*20)

# 创建大小分别为 3x2 和 4x2 的随机数矩阵
P = torch.randn(3, 2) * 0.01
Q = torch.randn(4, 2) * 0.01

print('P:\n', P)
print('Q:\n', Q)

# 对 P 进行形状变换得到 Q 的转置
QT = Q.t()

# 对 P 和 QT 求内积
res_2 = torch.mm(P, QT)
print('内积结果:\n', res_2)

******************** 第二题 ********************
P:
 tensor([[-0.0050,  0.0143],
        [ 0.0047, -0.0081],
        [ 0.0038,  0.0028]])
Q:
 tensor([[-0.0190, -0.0009],
        [ 0.0017, -0.0224],
        [-0.0080,  0.0022],
        [ 0.0194,  0.0024]])
内积结果:
 tensor([[ 8.3229e-05, -3.2897e-04,  7.1044e-05, -6.3631e-05],
        [-8.2533e-05,  1.8945e-04, -5.5094e-05,  7.2181e-05],
        [-7.4842e-05, -5.7141e-05, -2.4256e-05,  8.0655e-05]])


# 3.
给定公式 𝑦3 = 𝑦1 + 𝑦2 = 𝑥^2 + 𝑥^3
，且 𝑥 = 1。利用学习所得到的Tensor的相关知识，求𝑦3对的梯
度𝑥，即𝑑𝑦3/𝑑𝑥 。
要求首先需要将给定的公式转化为 PyTorch 中的表达式，即先定义变量 x 和 y1，然后通过 y3 = y1 + y2 和 y1 = x^2 得到 y3。然后再调用 backward() 方法计算梯度。
***
### 解:
在计算过程中，需要使用 torch.no_grad() 上下文管理器来中断对 x^3 的梯度追踪，因为我们只需要求解 dy3/dx，而 dy3/dx^3=0，不需要对 x^3 求梯度。在计算过程中，在计算 𝑥^3 时中断梯度的追踪，观察结果并进行原因分析
提示, 可使用 with torch.no_grad()， 举例:
with torch.no_grad():
y2 = x * 3

In [18]:
# 第三题
print('*'*20, '第三题', '*'*20)
# 定义变量 x 和 y1
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2

# 使用 torch.no_grad() 中断梯度追踪，计算 y2 = x^3
with torch.no_grad():
    y2 = x ** 3

# 计算 y3 = y1 + y2
y3 = y1 + y2

# 计算 dy3/dx
y3.backward()

# 输出结果，即 dy3/dx
print(x.grad)

******************** 第三题 ********************
tensor(2.)
